############################ Default configuration #########################
baseURL = "https://semba-blog.netlify.com/"
languageCode = "en-us"
# site title 
title = "pinab"
# theme
theme = "northendlab-hugo"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


########################### Navigation ###################################

# main menu
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1

[[menu.main]]
URL = "tools"
name = "tools"
weight = 2

[[menu.main]]
URL = "projects"
name = "Projects"
weight = 3

# footer menu
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1

[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2


######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/pinab_logo.svg"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2019 [Semba](https://semba-blog.netlify.com) All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true


####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Semba <br> oceanographer <br> and data science"
image = "images/banner/illustration.svg"


######################## call to action ###############################
[params.cta]
enable = true
image = "images/link_R.svg"
title = "Get the best post in R"
description = "In this blog I write post that explain how to use R programming languages for data science"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://semba-blog.netlify.com/"


############################## Social Site ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "#"
